### PR TITLE
Replace PocketSocket with native ios websockets

### PR DESCRIPTION
**Pull request by legion151**
With iOS 13.x websockets became available. 
Since we ran into probs with this package as described in #63 - we now use these instead of PocketSocket. PocketSocket is still contained for legacy support. I guess #63 is still an issue there. 
On iOS 13 devices we couldn't reproduce it. 

This PR also upgrades the demo to {N} 6.x.

### CODE REVIEW

**Comment by NathanaelA** [comment]
Awesome -- I'll try and test this today!

**Comment by coolsun** [comment]
> Awesome -- I'll try and test this today!

@NathanaelA, we got stuck by this issue for our IOT app mqtt feature release because mqtt silently crashed on connect/subscribe due to an error in PocketSocket.  There is no other alternative now and mqtt monitoring app seems a great utility for IOT websites like my customer.  Do you have an ETA for replacing PocketSocket with iOS native websockets?  Thanks!

**Comment by NathanaelA** [comment]
I have integrated this into the new 2.0 version.   Do to a lot of refactoring (updating code base to ES6 code) that I was doing before trying to merge this PR locally, I was unable to merge it directly, but basically merged it manually into my 2.0 branch.  Thank you.  If you have an email and name, I'll add you to the contributors in the JSON.

**Comment by legion151** [comment]
Thanks for mergin - don't really feel like a contributor yet ;)

**Pull request closed without merging**
